/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package fooSb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Projet service. Represents a row in the &quot;FOO_Projet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fooSb.model.impl.ProjetModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fooSb.model.impl.ProjetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Projet
 * @see fooSb.model.impl.ProjetImpl
 * @see fooSb.model.impl.ProjetModelImpl
 * @generated
 */
@ProviderType
public interface ProjetModel extends BaseModel<Projet>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a projet model instance should use the {@link Projet} interface instead.
	 */

	/**
	 * Returns the primary key of this projet.
	 *
	 * @return the primary key of this projet
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this projet.
	 *
	 * @param primaryKey the primary key of this projet
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this projet.
	 *
	 * @return the uuid of this projet
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this projet.
	 *
	 * @param uuid the uuid of this projet
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the projet ID of this projet.
	 *
	 * @return the projet ID of this projet
	 */
	public long getProjetId();

	/**
	 * Sets the projet ID of this projet.
	 *
	 * @param projetId the projet ID of this projet
	 */
	public void setProjetId(long projetId);

	/**
	 * Returns the group ID of this projet.
	 *
	 * @return the group ID of this projet
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this projet.
	 *
	 * @param groupId the group ID of this projet
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this projet.
	 *
	 * @return the company ID of this projet
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this projet.
	 *
	 * @param companyId the company ID of this projet
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this projet.
	 *
	 * @return the user ID of this projet
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this projet.
	 *
	 * @param userId the user ID of this projet
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this projet.
	 *
	 * @return the user uuid of this projet
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this projet.
	 *
	 * @param userUuid the user uuid of this projet
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this projet.
	 *
	 * @return the user name of this projet
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this projet.
	 *
	 * @param userName the user name of this projet
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this projet.
	 *
	 * @return the create date of this projet
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this projet.
	 *
	 * @param createDate the create date of this projet
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this projet.
	 *
	 * @return the modified date of this projet
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this projet.
	 *
	 * @param modifiedDate the modified date of this projet
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the town of this projet.
	 *
	 * @return the town of this projet
	 */
	@AutoEscape
	public String getTown();

	/**
	 * Sets the town of this projet.
	 *
	 * @param town the town of this projet
	 */
	public void setTown(String town);

	/**
	 * Returns the is single of this projet.
	 *
	 * @return the is single of this projet
	 */
	public boolean getIsSingle();

	/**
	 * Returns <code>true</code> if this projet is is single.
	 *
	 * @return <code>true</code> if this projet is is single; <code>false</code> otherwise
	 */
	public boolean isIsSingle();

	/**
	 * Sets whether this projet is is single.
	 *
	 * @param isSingle the is single of this projet
	 */
	public void setIsSingle(boolean isSingle);

	/**
	 * Returns the age of this projet.
	 *
	 * @return the age of this projet
	 */
	public int getAge();

	/**
	 * Sets the age of this projet.
	 *
	 * @param age the age of this projet
	 */
	public void setAge(int age);

	/**
	 * Returns the birth day of this projet.
	 *
	 * @return the birth day of this projet
	 */
	public Date getBirthDay();

	/**
	 * Sets the birth day of this projet.
	 *
	 * @param birthDay the birth day of this projet
	 */
	public void setBirthDay(Date birthDay);

	/**
	 * Returns the firstand last name of this projet.
	 *
	 * @return the firstand last name of this projet
	 */
	@AutoEscape
	public String getFirstandLastName();

	/**
	 * Sets the firstand last name of this projet.
	 *
	 * @param firstandLastName the firstand last name of this projet
	 */
	public void setFirstandLastName(String firstandLastName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(fooSb.model.Projet projet);

	@Override
	public int hashCode();

	@Override
	public CacheModel<fooSb.model.Projet> toCacheModel();

	@Override
	public fooSb.model.Projet toEscapedModel();

	@Override
	public fooSb.model.Projet toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}